<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net6.0;net8.0</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <SignAssembly>true</SignAssembly>
    <PackageTags>$(PackageTags)</PackageTags>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <Import Project="$(PublicAssemblyProps)" />
  <ItemGroup>
    <Folder Include="Engine\x32" />
    <Folder Include="Internal\x32" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Memory" Version="4.6.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.0" />
    <PackageReference Include="PolySharp" Version="1.13.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
