<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net6.0;net8.0</TargetFrameworks>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\K4os.Compression.LZ4.Streams\K4os.Compression.LZ4.Streams.csproj" />
    <ProjectReference Include="..\K4os.Compression.LZ4.Tests\K4os.Compression.LZ4.Tests.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
